#pragma once 
#ifndef SHADER_INFO_H 
#define SHADER_INFO_H 
/*
 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ 
SHADER INFORMATION. Shader enums, uniforms, etc... 
Generated by a python script shader_info_generator.py 
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ 
 */ 
// SCENE_3D SHADER SECTION 
typedef enum 
{
    SCENE_3D_DEFINE_TEXCOORD_ATTRIB,
    SCENE_3D_DEFINE_COLOR_ATTRIB,
    SCENE_3D_DEFINE_COLOR_8BIT,
    SCENE_3D_DEFINE_NORMAL_ATTRIB,
    SCENE_3D_DEFINE_TANGENT_ATTRIB,
    SCENE_3D_DEFINE_BITANGENT_ATTRIB,
    SCENE_3D_DEFINE_TEXTUREINDEX_ATTRIB,
    SCENE_3D_DEFINE_INSTANCE_MAT3,
    SCENE_3D_DEFINE_INSTANCE_UV,
    SCENE_3D_DEFINE_INSTANCE_COLOR,
    SCENE_3D_DEFINE_INSTANCE_CUSTOM,
    SCENE_3D_DEFINE_USE_UNIFORM_CAMERA_MATRIX,
    SCENE_3D_DEFINE_BILLBOARD_SHADOWS,
    SCENE_3D_DEFINE_USE_TEXTURE_ARR,
    SCENE_3D_DEFINE_SAMPLE_ALBEDO,
    SCENE_3D_DEFINE_SEMI_TRANSPARENT_PASS,
    SCENE_3D_DEFINE_MAX
}SCENE_3D_SHADER_DEFINES; 

typedef enum 
{
    SCENE_3D_UNIFORM_CAMERAMATRIX,
    SCENE_3D_UNIFORM_MAX
}SCENE_3D_SHADER_UNIFORMS; 

static const char* SCENE_3D_DEFINES_STR[] = 
{
    "TEXCOORD_ATTRIB", 
    "COLOR_ATTRIB", 
    "COLOR_8BIT", 
    "NORMAL_ATTRIB", 
    "TANGENT_ATTRIB", 
    "BITANGENT_ATTRIB", 
    "TEXTUREINDEX_ATTRIB", 
    "INSTANCE_MAT3", 
    "INSTANCE_UV", 
    "INSTANCE_COLOR", 
    "INSTANCE_CUSTOM", 
    "USE_UNIFORM_CAMERA_MATRIX", 
    "BILLBOARD_SHADOWS", 
    "USE_TEXTURE_ARR", 
    "SAMPLE_ALBEDO", 
    "SEMI_TRANSPARENT_PASS", 
};
static const char* SCENE_3D_UNIFORMS_STR[] = 
{
    "u_cameraMatrix", 
};
static const char* SCENE_3D_TEXTURES_STR[] = 
{
    "texture_arr", 
    "texture_sample_albedo", 
};

// POST_PROCESS SHADER SECTION 
typedef enum 
{
    POST_PROCESS_DEFINE_USE_REINHARD_TONEMAP,
    POST_PROCESS_DEFINE_USE_UNCHARTED2_TONEMAP,
    POST_PROCESS_DEFINE_USE_ACES_TONEMAP,
    POST_PROCESS_DEFINE_USE_FXAA,
    POST_PROCESS_DEFINE_USE_FOG,
    POST_PROCESS_DEFINE_USE_BLOOM,
    POST_PROCESS_DEFINE_MAX
}POST_PROCESS_SHADER_DEFINES; 

typedef enum 
{
    POST_PROCESS_UNIFORM_GAMMA,
    POST_PROCESS_UNIFORM_EXPOSURE,
    POST_PROCESS_UNIFORM_BLOOMSTRENGTH,
    POST_PROCESS_UNIFORM_BRIGHTNESS,
    POST_PROCESS_UNIFORM_CONTRAST,
    POST_PROCESS_UNIFORM_SATURATION,
    POST_PROCESS_UNIFORM_FOGCOLOR,
    POST_PROCESS_UNIFORM_HEIGHTFOGDENSITY,
    POST_PROCESS_UNIFORM_HEIGHTFOGMIN,
    POST_PROCESS_UNIFORM_HEIGHTFOGMAX,
    POST_PROCESS_UNIFORM_HEIGHTFOGCURVE,
    POST_PROCESS_UNIFORM_DEPTHFOGDENSITY,
    POST_PROCESS_UNIFORM_DEPTHFOGBEGIN,
    POST_PROCESS_UNIFORM_DEPTHFOGEND,
    POST_PROCESS_UNIFORM_DEPTHFOGCURVE,
    POST_PROCESS_UNIFORM_DEPTHFOGENABLED,
    POST_PROCESS_UNIFORM_HEIGHTFOGENABLED,
    POST_PROCESS_UNIFORM_MAX
}POST_PROCESS_SHADER_UNIFORMS; 

static const char* POST_PROCESS_DEFINES_STR[] = 
{
    "USE_REINHARD_TONEMAP", 
    "USE_UNCHARTED2_TONEMAP", 
    "USE_ACES_TONEMAP", 
    "USE_FXAA", 
    "USE_FOG", 
    "USE_BLOOM", 
};
static const char* POST_PROCESS_UNIFORMS_STR[] = 
{
    "u_Gamma", 
    "u_Exposure", 
    "u_BloomStrength", 
    "u_Brightness", 
    "u_Contrast", 
    "u_Saturation", 
    "u_fogColor", 
    "u_heightFogDensity", 
    "u_heightFogMin", 
    "u_heightFogMax", 
    "u_heightFogCurve", 
    "u_depthFogDensity", 
    "u_depthFogBegin", 
    "u_depthFogEnd", 
    "u_depthFogCurve", 
    "u_depthFogEnabled", 
    "u_heightFogEnabled", 
};
static const char* POST_PROCESS_TEXTURES_STR[] = 
{
    "depth_texture", 
    "MainSceneTexture", 
    "BloomSceneTexture", 
};

// DEFERRED_SCENE SHADER SECTION 
typedef enum 
{
    DEFERRED_SCENE_DEFINE_USE_SSAO,
    DEFERRED_SCENE_DEFINE_USE_DIR_SHADOWS,
    DEFERRED_SCENE_DEFINE_MAX
}DEFERRED_SCENE_SHADER_DEFINES; 

typedef enum 
{
    DEFERRED_SCENE_UNIFORM_SHADOWSAMPLEKERNELS,
    DEFERRED_SCENE_UNIFORM_SHADOWSAMPLEAMOUNT,
    DEFERRED_SCENE_UNIFORM_SHADOWQUALITYRADIUS,
    DEFERRED_SCENE_UNIFORM_MAXLIGHTCOUNT,
    DEFERRED_SCENE_UNIFORM_MAX
}DEFERRED_SCENE_SHADER_UNIFORMS; 

static const char* DEFERRED_SCENE_DEFINES_STR[] = 
{
    "USE_SSAO", 
    "USE_DIR_SHADOWS", 
};
static const char* DEFERRED_SCENE_UNIFORMS_STR[] = 
{
    "u_shadowSampleKernels", 
    "u_shadowSampleAmount", 
    "u_shadowQualityRadius", 
    "u_maxLightCount", 
};
static const char* DEFERRED_SCENE_TEXTURES_STR[] = 
{
    "gNormalMetal", 
    "gColorRough", 
    "depth_texture", 
    "SSAO_texture", 
    "shadowMapsDepth", 
    "brdfLUT", 
    "irradianceMap", 
    "preFilterMap", 
};

// SSAO SHADER SECTION 
typedef enum 
{
    SSAO_DEFINE_PASS_ACCUM,
    SSAO_DEFINE_PASS_BLUR,
    SSAO_DEFINE_PASS_UPSAMPLE,
    SSAO_DEFINE_MAX
}SSAO_SHADER_DEFINES; 

typedef enum 
{
    SSAO_UNIFORM_RADIUS,
    SSAO_UNIFORM_BIAS,
    SSAO_UNIFORM_STRENGTH,
    SSAO_UNIFORM_SECONDPASS,
    SSAO_UNIFORM_VIEWPORTSIZE,
    SSAO_UNIFORM_MAX
}SSAO_SHADER_UNIFORMS; 

static const char* SSAO_DEFINES_STR[] = 
{
    "PASS_ACCUM", 
    "PASS_BLUR", 
    "PASS_UPSAMPLE", 
};
static const char* SSAO_UNIFORMS_STR[] = 
{
    "u_radius", 
    "u_bias", 
    "u_strength", 
    "u_secondPass", 
    "u_viewportSize", 
};
static const char* SSAO_TEXTURES_STR[] = 
{
    "depth_texture", 
    "normal_texture", 
    "noise_texture", 
    "ssao_texture", 
    "halfsize_ao_texture_nearest", 
    "halfsize_ao_texture_linear", 
    "fullsize_depth_texture", 
};

// DOF SHADER SECTION 
typedef enum 
{
    DOF_DEFINE_COC_PASS,
    DOF_DEFINE_COMPOSITE,
    DOF_DEFINE_BOKEH_CIRCULAR,
    DOF_DEFINE_BOKEH_BOX,
    DOF_DEFINE_MAX
}DOF_SHADER_DEFINES; 

typedef enum 
{
    DOF_UNIFORM_VIEWPORTSIZE,
    DOF_UNIFORM_NEARBEGIN,
    DOF_UNIFORM_NEARBLURSIZE,
    DOF_UNIFORM_FARBEGIN,
    DOF_UNIFORM_FARBLURSIZE,
    DOF_UNIFORM_BLUR_SIZE,
    DOF_UNIFORM_BLUR_SCALE,
    DOF_UNIFORM_BLUR_STEPS,
    DOF_UNIFORM_SECOND_PASS,
    DOF_UNIFORM_MAX
}DOF_SHADER_UNIFORMS; 

static const char* DOF_DEFINES_STR[] = 
{
    "COC_PASS", 
    "COMPOSITE", 
    "BOKEH_CIRCULAR", 
    "BOKEH_BOX", 
};
static const char* DOF_UNIFORMS_STR[] = 
{
    "u_viewportSize", 
    "u_nearBegin", 
    "u_nearBlurSize", 
    "u_farBegin", 
    "u_farBlurSize", 
    "u_blur_size", 
    "u_blur_scale", 
    "u_blur_steps", 
    "u_second_Pass", 
};
static const char* DOF_TEXTURES_STR[] = 
{
    "depth_texture", 
    "scene_texture", 
    "blur_texture", 
};

// COPY SHADER SECTION 
typedef enum 
{
    COPY_UNIFORM_VIEWPORTSIZE,
    COPY_UNIFORM_FILTERRADIUS,
    COPY_UNIFORM_UVMULTIPLIER,
    COPY_UNIFORM_MAX
}COPY_SHADER_UNIFORMS; 

static const char* COPY_UNIFORMS_STR[] = 
{
    "u_viewportSize", 
    "u_filterRadius", 
    "u_uvMultiplier", 
};
static const char* COPY_TEXTURES_STR[] = 
{
    "source_texture", 
};

// BRDF SHADER SECTION 
typedef enum 
{
    BRDF_UNIFORM_SAMPLECOUNT,
    BRDF_UNIFORM_MAX
}BRDF_SHADER_UNIFORMS; 

static const char* BRDF_UNIFORMS_STR[] = 
{
    "u_sampleCount", 
};
// GODRAY SHADER SECTION 
typedef enum 
{
    GODRAY_DEFINE_RAYMARCH_PASS,
    GODRAY_DEFINE_BLUR_PASS,
    GODRAY_DEFINE_COMPOSITE_PASS,
    GODRAY_DEFINE_MAX
}GODRAY_SHADER_DEFINES; 

typedef enum 
{
    GODRAY_UNIFORM_VIEWPORTSIZE,
    GODRAY_UNIFORM_MAXSTEPS,
    GODRAY_UNIFORM_SCATTERING,
    GODRAY_UNIFORM_FOGCURVE,
    GODRAY_UNIFORM_SECONDPASS,
    GODRAY_UNIFORM_MAX
}GODRAY_SHADER_UNIFORMS; 

static const char* GODRAY_DEFINES_STR[] = 
{
    "RAYMARCH_PASS", 
    "BLUR_PASS", 
    "COMPOSITE_PASS", 
};
static const char* GODRAY_UNIFORMS_STR[] = 
{
    "u_viewportSize", 
    "u_maxSteps", 
    "u_scattering", 
    "u_fogCurve", 
    "u_secondPass", 
};
static const char* GODRAY_TEXTURES_STR[] = 
{
    "half_size_depth_texture", 
    "full_size_depth_texture", 
    "fog_texture", 
    "shadowMapsDepth", 
};


#endif